### ISSUE TITLE
Use WinGet Releaser to package to WinGet

### ISSUE THREAD

**Issue by russellbanks** [Xanthus58/Valorant-Randomizer#2]
Hi, I would suggest using [WinGet Releaser](https://bittu.eu.org/docs/wr-intro/) to submit future packages for this project to winget-pkgs.

It is a GitHub actions workflow that will run on every release, retrieve the installer from the GitHub release assets and automatically create a PR to winget-pkgs with the new update (from your account with a token). I saw that with 1.3.2 you tried to overwrite the previous version on winget-pkgs - I'm not sure whether this is intentional but WinGet Releaser will allow you to do this if you do only wish to have the latest version on winget-pkgs.

It would look like this:

```yml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: Xanthus58.ValorantRandomizer
          installers-regex: '\.exe$'
          delete-previous-version: 'true' # Optional
          token: ${{ secrets.WINGET_TOKEN }}
```

I'm happy to make a PR for this change to this repo :)
